apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-config
data:
  SPRING_PROFILES_ACTIVE: "prod"
  EUREKA_URL: "http://eureka-server:8761/eureka/"
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"

  AUTH_PORT: "8081"
  INVENTORY_PORT: "8083"
  PRODUCT_PORT: "8082"
  ORDER_PORT: "8084"
  NOTIFICATION_PORT: "9000"
  UPLOAD_PORT: "8087"
  GATEWAY_PORT: "8080"

  INVENTORY_URL: "http://inventory-service:8083"
